### ISSUE TITLE
Images no longer "click-to-expand" leading to challenging readability

### ISSUE THREAD

**Issue by strideynet** [gravitational/docs-website#26]
We have a fair few information dense graphics across our documentation, and I've found it hard reading them on the new docs site. On the old docs site, I could click on a graphic to have it pop-over in a larger size. This doesn't seem to happen on the new site. If we can't add this functionality, then we probably need to do a sweep of diagrams and simplify/break them up.

**Comment by hugoShaka** [comment]
Same problem for screenshots, for example [the OIDC guide](https://goteleport.com/docusaurus/ver/17.x/admin-guides/access-controls/sso/oidc#using-the-web-ui):

- before: ![Image](https://github.com/user-attachments/assets/58283c64-3993-48b5-becf-96371a782c51)
- after ![Image](https://github.com/user-attachments/assets/ee302af6-1449-4bd0-b99b-5e3c8e2450d4)
