### ISSUE TITLE
Redesign Docs site navigation

### ISSUE THREAD

**Issue by roraback** [gravitational/docs-website#45]
Sections (names TBD—need to refine our language to ensure it resonates with new and returning users):
* Homepage / Dashboard that links out to useful sections or articles (see Stripe docs for a great example of this)
* Getting Started
* Managing Access
* End-User Guide (Connecting to Infrastructure)
* Tutorials
* Reference

Also want to feature search more prominently!

Photos of Post-It notes from the brainstorming session:
![Image](https://github.com/gravitational/docs-website/assets/1095531/03376508-de6e-49ec-bec0-c989394f4b44)

![Image](https://github.com/gravitational/docs-website/assets/1095531/5c7cbd5a-e79b-43cb-b649-60617553c5ff)

![Image](https://github.com/gravitational/docs-website/assets/1095531/ef0f0955-4fb6-43fc-9696-4224d87e71e0)

![Image](https://github.com/gravitational/docs-website/assets/1095531/aff0c12a-86e3-46ca-91c2-2507412d2510)

![Image](https://github.com/gravitational/docs-website/assets/1095531/7369b91e-373c-423e-8468-40af1112ba80)

**Comment by ptgott** [comment]
Closing this for now, since we have implemented an approach to docs site navigation with a reduced set of top-level categories. We can create more focused issues for concrete work items that follow from the new navigation approach.
