### ISSUE TITLE
Syntax highlighting is performing worse than the Next-based docs

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/docs-website#6]
Compared to the previous docs, syntax highlighting is not working in most places. This is a meta issue identifying everything wrong with syntax highlighting, as there are multiple root-causes, it might make sense to split it into several smaller issues.

I think there are several issues:
- some languages don't seem to be highlighted:
  ![Image](https://github.com/user-attachments/assets/e4066f40-723b-4a88-ac58-58ccf594a49c)
  - HCL Terraform code: https://goteleport.com/docusaurus/admin-guides/infrastructure-as-code/terraform-provider/local#step-22-run-the-terraform-provider
  - ini config: https://goteleport.com/docusaurus/admin-guides/access-controls/idps/saml-grafana#step-23-configure-grafana-to-recognize-teleports-identity-provider
- some highlighters are producing inconsistent highlighting
   ![Image](https://github.com/user-attachments/assets/ba36d130-dac2-4a06-a681-caf5ec6f16fb)

  - the new YAML highlighter only identifies strings if they are between quotes (broken YAML parsing): https://goteleport.com/docusaurus/admin-guides/deploy-a-cluster/multi-region-blueprint/#deploying-teleport (look at the `auth.teleportConfig.teleport.storage.conn_string`)
  - the new YAML highlighter incorrectly identifies port numbers in a string as integers: https://goteleport.com/docusaurus/enroll-resources/application-access/guides/connecting-apps#cors-support-for-preflight-requests
- the command line vs output highlighting is not implemented:
  ![Image](https://github.com/user-attachments/assets/8564ff5f-2652-487b-9a1c-96c7b7015460)
  - before: it was visually clear what were the commands, and what were the outputs: e.g. the tsh login check: https://goteleport.com/docs/admin-guides/access-controls/idps/saml-grafana/#prerequisites
  - now: everything is using the same grey and there's no difference between a command and its output: https://goteleport.com/docusaurus/admin-guides/access-controls/idps/saml-grafana#prerequisites
  - also:
    - the copy button now copies the leading `$`: https://github.com/gravitational/docs-website/issues/8
    - the copy button now copies the output
    - there is no per-command copy button anymore
- the color scheme is different, less vibrant and clear than the previous one:
  ![Image](https://github.com/user-attachments/assets/131dc8fb-2bc6-494b-a3fc-8565ef5405ad)
  - YAML comments contrast is too low and hardly readable: https://goteleport.com/docusaurus/admin-guides/access-controls/idps/saml-grafana#step-33-add-service-provider-metadata-to-teleport
  - SQL query highlighting almost looks like no highlighting happened: https://goteleport.com/docusaurus/admin-guides/deploy-a-cluster/multi-region-blueprint#teleport-backend-configuration

**Comment by taraspos** [comment]
This page seems to be highlithing code snipped poorly:
- https://docusaurus.goteleport.com/docusaurus/ips/
![Image](https://github.com/user-attachments/assets/c01bda68-0c5e-4598-acf5-b75cc0a8945e)
