### ISSUE TITLE
Searching changelog does not point to the general endpoint

### ISSUE THREAD

**Issue by tenaciousdlg** [gravitational/docs-website#84]
Searching "changelog" with the inkeep search wizard links to https://goteleport.com/docs/changelog/#409
![Image](https://github.com/user-attachments/assets/eda79f3f-c5d2-4d39-b450-25144c37b0f5)
This should link to just https://goteleport.com/docs/changelog/

**Comment by benarent** [comment]
this issue should be fixed, I pinged the inkeep team and they fixed it.
